### ISSUE TITLE
occassionally the context for "create INP file" is sometimes incorrect 

### ISSUE THREAD

**Issue by samerps** [samerps/Blender-FastHenry#31]
error
RuntimeError: Operator bpy.ops.object.bfh_create_inp.poll() failed, context is incorrect
Error: Python: Traceback (most recent call last):
  File "C:\Users\samer\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\user_default\blender_fasthenry\operators\FH_run_all.py", line 29, in execute
    bpy.ops.object.bfh_create_inp()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Operator bpy.ops.object.bfh_create_inp.poll() failed, context is incorrect
Executable is running in the background...

**Comment by samerps** [comment]
fixed in https://github.com/samerps/Blender-FastHenry/pull/37
